### ISSUE TITLE
Testing: introduce mock objects for calling LLM APIs

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter#17]
We currently rely on calling APIs (mainly OpenAI) inside our tests. To isolate the unit tests from the outside conditions of API connectivity (having a key, reacting to model updates), it would probably be best to rely on mock classes that generate fake API responses for the individual tests, e.g. embeddings or text summaries.

This way, the CI procedure can safely be moved to a GitHub runner without the risk of accumulating high API costs, for instance in the case of a workflow bug that causes many runs.

**Comment by slobentanzer** [comment]
@fengsh27 as I am currently noticing, it is not even purely about the cost / connectivity issue. PRs do not have access to repository secrets because that may cause security issues (understandably). So we cannot use API keys in CI that runs on PRs.

**Comment by fengsh27** [comment]
@slobentanzer , Sorry for the late reply, I just notice this comment and your comments in https://github.com/biocypher/biochatter/pull/24#issuecomment-1792890944. I will look into the [PR# 24](https://github.com/biocypher/biochatter/pull/24).

I'm intrigued that PRs can't access repository secrets. Because the secrets are specially designed for actions to access, and their values can only be seen by repository owner. Here is the documentation for secrets https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions. Additionally, please pay attention to step 3 of the documentation (In the "Security" section of the sidebar, select  Secrets and variables, then click **Actions**.)

**Comment by fengsh27** [comment]
@slobentanzer , BTW we need these secrets:
![image](https://github.com/biocypher/biochatter/assets/123769183/47b2ae32-6bb9-42ed-bb5f-80964c25999f)

**Comment by slobentanzer** [comment]
We do have these secrets in the repo; as long as we're inside the org (ie, a PR from within `biocypher`), it is fine. CI is passion as long as we're on main or inside the org. The issue is with PRs from foreign repos, because they could inject malicious code and steal the secrets. See e.g. here: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Since the PR came from Andi's private GitHub account, secrets were not available.

**Comment by fengsh27** [comment]
I got it. That make sense.
