### ISSUE TITLE
Multi-word label query generation

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter#59]
For labels such as CellType, tokenisation may not be fortunate. Convert to lower sentence case before entity selection?

Write benchmark for several multi-word cases.

**Comment by YY-SONG0718** [comment]
- [ ] add multi-word label entity and example relationship(s) to test schema
- [ ] write unit tests for multi-word label query generation
- [ ] try to run pytest
- [ ] consolidate format of test results (scores)

**Comment by slobentanzer** [comment]
@YY-SONG0718 I just realised that I know examples where multi-word tokenisation appears to work fine with the PascalCase labels. For instance, in collectri we have `TranscriptionFactor` nodes, and in the original biochatter tests, there are relationships like `ProteinToPhenotypeAssociation`, which should in theory be even more problematic, but I didn't see the issue as you did with `CellType`.

How can we be sure whether this is a consistent problem with tokenisation of the PascalCase labels? Should we have more examples (representative multi-word labels from biomed or even other contexts) in the basic tests of the benchmark module (`benchmark/test_biocypher_query_generation.py`)?

**Comment by YY-SONG0718** [comment]
Thanks for the info @slobentanzer ! I think the issue may be LLM having different performance on different domain questions. I am looking into the codes in `prompts.py` to see if there is any process that needs to 'comprehend' the labels, or just need to grab some info from the dictionary using the labels as keys. The former can benefit from using lower-case labels due to tokenization, and the latter is a prompt optimization problem that can depend on the domain. Although, I am not sure if the latter case will also be affected by tokenization?

So far I found these problems in the benchmark tests on `CellType` but not on the original benchmarks:

Properties:
gpt-3.5-turbo cannot get the properties right.

Relationships:
Both gpt-3.5-turbo and gpt-4 also take other relationships that only have one entity as source or target, when there is exactly a relationship with the exact source and target. From my understanding, only the relationship with both should be kept?

On my schema the correct cell type name property (literally cell_type_name) still cannot be selected, so it got hallucinated into 'name' in the final cypher query in both gpts. Also in another example 'OrthologousGroups' property hallucination happened when I asked questions about a specific id which is not to be filtered by any properties. 

I can try to change the prompt to constrain the model which I think is the most helpful at the moment. I also agree that we can include more typical examples in the benchmark test - try to span a wider range of biological domains.

**Comment by slobentanzer** [comment]
Agree and makes sense. I would emphasise extending the benchmark part to create a solid foundation for the evaluation of prompt sets and different models, also future ones.

> if there is any process that needs to 'comprehend' the labels

Kind of 'yes and no'; the labels just need to be selected, but the selection needs to happen with a semantic understanding of the question the user asked the model, so this is tricky to answer. We could think about dedicated benchmark questions for this issue. For instance, and related to your later question, it was quite hard to get the model to select the semantically 'wrong' label for the relationship selection (when the schema forces selection of a 'wrong' relationship because the correct one does not connect the entities in question). It is a bit questionable how close this is to reality, but an interesting benchmark.

> Both gpt-3.5-turbo and gpt-4 also take other relationships that only have one entity as source or target, when there is exactly a relationship with the exact source and target. From my understanding, only the relationship with both should be kept?

I recently changed the logic in the relationship selection to enable selection of relationships where only one of the two partners is present. Being more strict (both need to be there) has other drawbacks that led to worse performance in my tests. I will think on how to formalise these for the benchmark as well. Maybe a two-stage process (selecting more broadly and then refining) could be useful.

> I can try to change the prompt to constrain the model

I think that is the most promising direction. However, if you play around with prompts, consider directly making it a benchmark set or at least recording the different prompts so we can make them a benchmark later. :)
